### ISSUE TITLE
Official bazel-mode

### ISSUE THREAD

**Issue by laurentlb** [brown/bazel-mode#1]
We've created a new repository: https://github.com/bazelbuild/emacs-bazel-mode (empty for now)

The goal is to make it the official bazel-mode.
If you're interested, your contributions are welcome.

Thanks!

**Comment by brown** [comment]
I've been maintaining a Bazel mode for Emacs here:  https://github.com/brown/bazel-mode
Would you like to mirror that repository or import it into the one you just created?

**Comment by laurentlb** [comment]
You can send a PR.
Someone else will do the same (https://github.com/codesuki/bazel-mode/issues/1), I don't know how much it overlaps.

**Comment by brown** [comment]
I'm happy to let you import my repo.  I would prefer that the code have a GNU license,
and that may be necessary, given that I've leveraged off of python-mode, which has that
license.

**Comment by condy0919** [comment]
@laurentlb You haven't reviewed pull requests for about four months :sob:
